### ISSUE TITLE
This app should be more than just decorator mixins

### ISSUE THREAD

**Issue by rockymeza** [fusionbox/django-decoratormixins#1]
@acatton mentioned the [WithNextUrlMixin](https://github.com/fusionbox/django-authtools/blob/master/authtools/views.py#L59-L76), which is quite useful as well.

I agree with him that it doesn't belong in django-authtools and that perhaps we could put that in this library.

If we're going to include more things than just the decorator mixins, then we should probably change the name of the project. Maybe something like django-viewmixins. We can talk about the name later.

I also think this makes the project structure that we discussed previously might not make that much sense anymore. I'm reminded of something that I heard during one of Raymond Hettinger's talks, which is that the import paths aren't for taxonomy. Maybe the API would be better if all of the mixins lived in the top-level package:

``` python
from viewmixins import WithNextUrlMixin, LoginRequiredMixin, VaryMixin
```

Thoughts?

**Comment by jxcl** [comment]
I think perhaps moving them all to one module might be a bit overkill, but I have already moved everything from the views/ package to the base directory. Deep nested structures are overkill, but I feel like in this case a flat package structure could be useful.

**Comment by jxcl** [comment]
This library already exists in the form of django-braces: https://github.com/brack3t/django-braces
